# Generated by Django 3.0.6 on 2020-05-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AlterField(
            model_name='project',
            name='desription',
            field=models.CharField(max_length=500),
        ),
    ]
